### ISSUE TITLE
[Feature Request] Transpose chords

### ISSUE THREAD

**Issue by artutra** [martijnversluis/ChordSheetJS#102]
How about adding a configuration to transpose all chords of the music?
This method should do the trick for each chord:
```
function transposeChord(chord, amount) {
    var scale = [["C"],
                 ["C#","Db"],
                 ["D"],
                 ["D#","Eb"],
                 ["E"],
                 ["F"],
                 ["F#","Gb"],
                 ["G"],
                 ["G#","Ab"],
                 ["A"],
                 ["A#","Bb"],
                 ["B"]];
    return chord.replace(/[CDEFGAB](#|b)?/g, function(match) {
        for (var i = scale.length - 1; i >= 0; i--) {
            if(scale[i].indexOf(match) != -1){
                var j = (i+amount) % scale.length;
                return scale[ j < 0 ? j + scale.length : j ][0];
            }
        }
    });
}

```

**Comment by martijnversluis** [comment]
Hi @artutra. This project does not parse on the chord level. I do have a separate project for that: https://github.com/martijnversluis/ChordJS. Additionally, if you look at this file in the ChordFiddle project, you can see how I combined ChordSheetJS and ChordJS: https://github.com/martijnversluis/ChordFiddle/blob/master/src/utils/chord_sheet_transformations.js

Please let me know if this is helpful.
