### ISSUE TITLE
ChordProParser - mark chorus

### ISSUE THREAD

**Issue by martijnversluis** [martijnversluis/ChordSheetJS#11]
Use `{start_of_chorus}` and `{end_of_chorus}` to mark the paragraph(s) in between as chorus

**Comment by filipblaauw** [comment]
Great project, looking forward to seeing support for chorus/verse directives. Would also be great to see support of comments ( shortcode {c} ) when and if the song has sections that can't be defines as verse or chorus, like bridge, intro, outro, solo, vamp, etc.

**Comment by martijnversluis** [comment]
@filipblaauw Thanks for your feedback! I just released `2.4.0` which adds support for `{c}` and `{comment}`.

**Comment by martijnversluis** [comment]
@filipblaauw Just released `2.8.0` with support for `{start_of_chorus}` (`{soc}`), `{end_of_chorus}` (`{eoc}`), `{start_of_verse}` and `{end_of_verse}`. This is only parser side though, the formatting will be handled in #17.
