### ISSUE TITLE
Is it wrong to use Transpose in a song that modulates within a song?

### ISSUE THREAD

**Issue by fuyunekojima** [martijnversluis/ChordSheetJS#1109]
For example, let's say I have a song that is in the basic key of E and transposes to G only in the chorus.
If I use `Song.transpose(-1)` for that song, the whole song will be in the key of Eb.
I want to transpose it like `E -> Eb, G -> F#`. Is it inappropriate to use `transpose()` for such a song?

**Comment by martijnversluis** [comment]
Hey @fuyunekojima. Thanks for reaching out!

If you want to transpose only the chorus, there are currently a few options:

- if it's part of the song that the chorus is always in G, I would recommend to just use the G-based chords in the chordpro source

- there is a `transpose` directive available, eg.:
```
{key: E}

{start_of_verse: Verse 1}
[E]Some [A]lyrics
{end_of_verse}

{start_of_chorus}
{transpose: G}
[E]Lyrics written in [A]A key
[E]But rendered in [A]G key
{end_of_chorus}
```
- you can use [`Song#mapItems`](https://github.com/martijnversluis/ChordSheetJS/blob/641911ef1fe8b93de9cba68277998effcb3ebd8a/src/chord_sheet/song.ts#L551) as inspiration for a custom function to only transpose choruses:

```js
function transposeChoruses(song) {
  const clonedSong = new Song();

  this.lines.forEach((line) => {
    clonedSong.addLine();

    line.items.forEach((item) => {
      const changedItem = item.clone();

      if (line.isChorus() && item instanceof ChorusLyricsPair) {
        changedItem = changedItem.transpose(4);
      }

      clonedSong.addItem(changedItem);
    });
  });

  return clonedSong;
```

Please let me know if this solves your problem! 👍
