### ISSUE TITLE
Attempting to parse `{start_of_abc}` directives throws exceptions

### ISSUE THREAD

**Issue by ChrisMBarr** [martijnversluis/ChordSheetJS#1155]
Similar to my old issue #907, this now mostly works when I parse the following data, but properties like `bodyParagraphs`, `expandedBodyParagraphs`, and `paragraphs` all throw exceptions when I try to access them

Here is my setup, just like in #907

```ts
import { ChordProParser } from 'chordsheetjs';

const chordProTestSong = `{title: Our Father}
{artist: Bethel Music}
{key: G}
{comment: Words and Music by Marcus Meier}

{gc:Intro:}
[G]  [C/E]  [C]

{sov}
Verse:
Our Fa[G]ther in Heaven
Hal[C]lowed be Your [D]name
Your Kin[G]gdom come quickly
Your w[C]ill be done the s[D]ame
{eov}

{soc}
Chorus:
On E[C]arth a[G/B]s it[Am] is in [Em]Heaven
Let He[D]aven come to
[C]Earth [G/B]as i[Am]t is in[Em] Heaven
Let He[D]aven [G]come
{eoc}

{sob}
Bridge 1:
Let Heaven c[C]ome, let Heaven[Em] come
Let Heaven c[C]ome, let Heaven[Em] come
{eob}

Bridge 2:
[C]Yours is the Kingdom, Yours is the p[D]ower
[Em]Yours is the glory [G/B]forever, amen
[C]Yours is the Kingdom, Yours is the p[D]ower
[Em]Yours is the glory [G/B]forever amen

{start_of_grid}
|| Am . . . | C . . . | D  . . . | F  . . . |
|  Am . . . | C . . . | E  . . . | E  . . . |
|  Am . . . | C . . . | D  . . . | F  . . . |
|  Am . . . | E . . . | Am . . . | Am . . . ||
{end_of_grid}

{start_of_abc}
X:1
T:The Gentle Breeze
M:2/4
L:1/8
R:Air
K:Em
E>F G/2E/2-E| {A}B2{^c/2B/2}A>B| G/2E/2-E d2| B/2^c/2d B/2c/2d| e>f d>f|\
e3 B| g>B f>B| ef| eB F>B| E4:|

{end_of_abc}

{start_of_ly}
\\relative { g'8\\( a b[ c b\\) a] g4 }
{end_of_ly}
`;

const parser = new ChordProParser();
const doc = parser.parse(chordProTestSong);
console.log(doc);
```

So `console.log(doc)` will return a parsed document, but `console.log(doc.bodyParagraphs)` will throw the following exception

```
C:\Users\chris\Projects\LyricConverter\node_modules\chordsheetjs\lib\index.js:14421
        return this.items.some((item)=>item.isRenderable());
                                            ^

TypeError: Cannot read properties of null (reading 'isRenderable')
    at C:\Users\chris\Projects\LyricConverter\node_modules\chordsheetjs\lib\index.js:14421:45
    at Array.some (<anonymous>)
    at $bc411321e9739719$var$Line.hasRenderableItems (C:\Users\chris\Projects\LyricConverter\node_modules\chordsheetjs\lib\index.js:14421:27)
    at C:\Users\chris\Projects\LyricConverter\node_modules\chordsheetjs\lib\index.js:15051:29
    at Array.forEach (<anonymous>)
    at $6f653df65dfdf4ef$var$Song.linesToParagraphs (C:\Users\chris\Projects\LyricConverter\node_modules\chordsheetjs\lib\index.js:15047:15)
    at get paragraphs [as paragraphs] (C:\Users\chris\Projects\LyricConverter\node_modules\chordsheetjs\lib\index.js:15034:21)
    at get bodyParagraphs [as bodyParagraphs] (C:\Users\chris\Projects\LyricConverter\node_modules\chordsheetjs\lib\index.js:14969:91)
    at Object.<anonymous> (C:\Users\chris\Projects\LyricConverter\csp.js:64:17)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
```

Here's what the whole object looks like in Chrome's console
![image](https://github.com/martijnversluis/ChordSheetJS/assets/463685/a68efbb1-328b-4b5b-8705-30ff02d241a8)

I've narrowed this down to everything between the `{start_of_abc}` and `{end_of_abc}` directives. These directives are listed as being one of the supported delegated environment directives on the ChordPro site: https://www.chordpro.org/chordpro/chordpro-directives/

I've also notice that parsing
```
{start_of_textblock align=right flush=right}
She died of the fever,
and nothing could save her
And that was the end of sweet Molly Malone
{end_of_textblock}
```
will throw this exception
```
PeggySyntaxError: Expected ":" or "}" but "a" found.
```

These are absolutely not critical for me though since I suspect most people aren't using these strange directives. I just care about extracting lyrics from these files. I just want my project not to break if they happen to be using these directives. Currently I am doing some manual string parsing to remove these directives before I pass it off to this parser, which works as a band-aid for me right now.

```ts
const parser = new ChordProParser();
const preProcessedStr = chordProTestSong
  .replace(/{start_of_abc}[\s\S]+?{end_of_abc}/, '')
  .replace(/{start_of_textblock.+?}[\s\S]+?{end_of_textblock}/, '');
const doc = parser.parse(preProcessedStr );
console.log(doc.bodyParagraphs);
```
Hooray it works now!

**Comment by martijnversluis** [comment]
Hey @ChrisMBarr. I just published `9.0.6`, it contains a fix for all supported sections including `start_of_abc`. `start_of_textblock` is not yet supported, I added [an issue](https://github.com/martijnversluis/ChordSheetJS/issues/1178) to the [board](https://github.com/martijnversluis/ChordSheetJS/projects/1?query=is:open+sort:updated-desc) to implement that.

**Comment by ChrisMBarr** [comment]
nice!  I was able to upgrade LyricConverter to v10 and removed my manual replacement for this directive, and all my unit tests pass no issue!

https://github.com/ChrisMBarr/LyricConverter/commit/529ad0e789b7267179b8d2f906c679a280b5c92b

Near my changes in there you'll see my temp workaround for the `start_of_textblock` issue, and I suppose I should mention the same is true for `start_of_svg` as well. I can open an issue for that if you'd like

**Comment by martijnversluis** [comment]
Cool! Nice the issue is resolved.

Feel free to create an issue for the implementation of `start_of_svg` 👍
