### ISSUE TITLE
Changing to # or b for entire song

### ISSUE THREAD

**Issue by beltonk** [martijnversluis/ChordSheetJS#1169]
Why not a simple way to useModifier() for ChordProParser() object directly?

**Comment by martijnversluis** [comment]
Great feature! Putting this on the [board](https://github.com/martijnversluis/ChordSheetJS/projects/1#card-92578450)!

**Comment by beltonk** [comment]
I combined ChordFiddle example into a single function, but would be great to support it natively.

public setFixChordModifier(modifier: Modifier): void {
    
    let processedSong = this.song.clone();
    processedSong.lines = processedSong.lines.map((line) => {
      const processedLine = line.clone();
      processedLine.items = line.items.map((item) => {
        if (item instanceof ChordSheetJS.ChordLyricsPair && item.chords) {
          let processedChordLyricsPair = item.clone();
          if (item.chords) {
            let parsedChord = Chord.parse(item.chords);               
            if (parsedChord) {
              processedChordLyricsPair.chords = (new Chord(parsedChord).useModifier(modifier)).toString();
              processedChordLyricsPair.chords = processedChordLyricsPair.chords.replace('B#', 'C');
              processedChordLyricsPair.chords = processedChordLyricsPair.chords.replace('Cb', 'B');
              processedChordLyricsPair.chords = processedChordLyricsPair.chords.replace('E#', 'F');
              processedChordLyricsPair.chords = processedChordLyricsPair.chords.replace('Fb', 'E');
              return processedChordLyricsPair;
            }
          } else {
            return processedChordLyricsPair;
          }
        }
        return item;
      });
      return processedLine;
    });
    this.song = processedSong;
  }

**Comment by martijnversluis** [comment]
Hey @beltonk. I just published `10.3.0`, which includes this feature: `song.useModifier(modifier)`.
