### ISSUE TITLE
[Feature Request] Tab render

### ISSUE THREAD

**Issue by artutra** [martijnversluis/ChordSheetJS#117]
Any plans to include the start_of_tabs and end_of_tabs directives?
I am making an opensource app with this lib and would be really usefull if the Song class already supported this directive.
Currently I need it just for a better formating of tabs on screen.
This is the source code: https://github.com/artutra/OpenChord

**Comment by martijnversluis** [comment]
Hey @artutra,

Sorry for the immense delay answering your question. 

I might add support for this directive in `ChordProParser`. Rendering the tabs, however, will be a major feature; I would not really know how to pull that off.

Are you looking for parsing support or rendering support, or both?

**Comment by artutra** [comment]
So, actually I ended up making my own [CustomHtmlDivFormatter](https://github.com/artutra/OpenChord/blob/master/app/utils/CustomHtmlDivFormatter.ts) to make the rendering (you can see the tests here [CustomHtmlDivFormatter-test](https://github.com/artutra/OpenChord/blob/master/__tests__/utils/CustomHtmlDivFormatter-test.tsx)). It is very simple but is working for now.
But still a parser would be very useful as there would be an implementation of the Tablature class that will make easier to build transpose methods for tabs and to make custom formatter with less work arounds.
