### ISSUE TITLE
Chord.normalize() does not normalize some slash chords properly

### ISSUE THREAD

**Issue by beltonk** [martijnversluis/ChordSheetJS#1171]
My case was:
Db7/Cb -> Db7/Cb (/Cb not normalized)

While other test cases are correct:

D/Cb -> D/B
Cb -> B
Cb7/Cb -> B7/B
E#7/Cb -> F7/B

C#/E# -> C#/F

Fb -> E
C/Fb -> C/E

No idea of the pattern...

**Comment by martijnversluis** [comment]
Hi @beltonk. Thanks for reaching out! Is the song key defined? And, if so, what is the key?

**Comment by beltonk** [comment]
yes, I did. setKey(“Db”):

**Comment by martijnversluis** [comment]
Hey @beltonk. I just published `9.0.7` that fixes the wrong normalization.
