### ISSUE TITLE
Issue importing Chord in TypeScript

### ISSUE THREAD

**Issue by beltonk** [martijnversluis/ChordSheetJS#1180]
I had a hard time to import Chord correctly in my Astro / TypeScript project.

Is there some typos in #72 https://github.com/martijnversluis/ChordSheetJS/blob/master/src/index.ts : export default ?

Chord missing -> CHORUS
Key missing -> INTERMEDIATE
template_helpers missing -> VERSE

**Comment by beltonk** [comment]
import { ChordProParser, HtmlTableFormatter, Song, ChordLyricsPair, Chord } from 'chordsheetjs';

SyntaxError: The requested module 'chordsheetjs' does not provide an export named 'Chord'

**Comment by beltonk** [comment]
The following would work:
import ChordSheetJS from 'chordsheetjs';
const { ChordProParser, HtmlTableFormatter, Song } = ChordSheetJS;

but 

import ChordSheetJS from 'chordsheetjs';
const { ChordProParser, HtmlTableFormatter, Song, Chord } = ChordSheetJS;

won't work

**Comment by martijnversluis** [comment]
Hey @beltonk. Thanks for reporting your issue. 

In old versions only the default export (import ChordSheetJS from 'chordsheetjs') existed. At some point I introduced named exports (`import { Chord } from 'chordsheetjs'`). For backwards compatibility I've never removed the default export. However, most new classes/constants have only been added as a named export.

The following should work for you:

```ts
import { Chord } from 'chordsheetjs';
```

Please let me know if this resolves the issue 👍

**Comment by beltonk** [comment]
While tsc works now, still have the following error while building:

import { Chord } from 'chordsheetjs';
              ^^^^^
SyntaxError: The requested module 'chordsheetjs' does not provide an export named 'Chord'

**Comment by beltonk** [comment]
My workaround is:
import pkg from 'chordsheetjs';
const { Chord } = pkg;

which can pass tsc and tsx, and also astro building, but failing astro check:

Property 'Chord' does not exist on type '{ CHORUS: string; ChordLyricsPair: typeof ChordLyricsPair; ChordProFormatter: typeof ChordProFormatter; ChordProParser: typeof ChordProParser; ChordSheetParser: typeof ChordSheetParser; ... 20 more ...; VERSE: string; }'.

so I have to skip the check before building...

**Comment by beltonk** [comment]
Can this be fixed please?

**Comment by martijnversluis** [comment]
Hey @beltonk. I published version `10.1.0`, which adds `Chord` to the default export. Can you test if that solves your issue?

**Comment by beltonk** [comment]
I tested it and now the error goes away. simply
```import ChordSheetJS from 'chordsheetjs';```

and can successfully use
```new ChordSheetJS.Chord()```
and
```ChordSheetJS.Chord.parse```

just like
ChordSheetJS.ChordProParser() and ChordSheetJS.HtmlDivFormatter
