### ISSUE TITLE
Error with sot / eot

### ISSUE THREAD

**Issue by beltonk** [martijnversluis/ChordSheetJS#1181]
This is the case with OLGA - Bon Jovi's I'll Be There For You, which contains:

`{sot}
	-------------------------------------|
	-------------------------------------|	
	-------------------------------------|
	--3/5--5--5/7--7--7/10--10--10/9--9--|
	-------------------------------------|
	-------------------------------------|

	-------------------------------------|
	-------------------------------------|
	-------------------------------------|
	--3/5--5--5/7--7--7/10--10--9--------|
	-------------------------------------|
	-------------------------------------|
{eot}`

**Comment by beltonk** [comment]
not sure why, just saw error: "Cannot read properties of null (reading 'isRenderable')"

**Comment by martijnversluis** [comment]
Hey @beltonk. Thanks for reaching out. I just published `9.0.6`, it contains a fix this bug.
