### ISSUE TITLE
New "Intro" chords category ? 

### ISSUE THREAD

**Issue by MercierCorentin** [martijnversluis/ChordSheetJS#1211]
Some chords shouldn't be placed on top of the text, like the ones below, because it would disrupt the formatting created by the author.

In the data I receive, these are indicated as chords but also specified not to be part of the song. Therefore, I wrapped them with `[...]` to make them look like annotations.

```
[Interlude]
[|(G) | G | Em | Em |]
[| C  | C | D  | D |]
```

The problem is that when I transpose in real time, I retrieve all elements with the `.chord` class to then transpose the chord and inject the new chord in JavaScript. So the wrapped chords are not transposed. This results in an inconsistent rendered chordSheet.

Did I handle this incorrectly, or do we need a new type of chord, for example, `.chord-no-tab`, to achieve what I want ? 

Thanks again for the great work !

**Comment by aonghas** [comment]
You can get around this by escaping the chords and annotations individually, ie.

```
[Interlude]
[| (][G][) | ][G][ | ][Em][ | ][Em][ |]
[| ][C][  | ][C][ | ][D][  | ][D][ |]
```
Then the chords will also be transposed.

Hope this helps.
