### ISSUE TITLE
[Bug/Issue] (B, C) & (E,F) In spanish Si# and Mi# does not exist.

### ISSUE THREAD

**Issue by hkfuertes** [martijnversluis/ChordSheetJS#1288]
I found an issue while printing the chords in Spanish and with #, I had to do this in my code to fix it:
```javascript
function printChord(chord, english){
    let parsed = Chord.parse(chord);
    if(english){
        return parsed?.toChordSymbolString("c")
    }else{
        return parsed?.useModifier('#').toChordSolfegeString("c").replace('Si#','Do').replace('Mi#','Fa')
    }
}
```
Basically the chords in spanish are:
Do(#), Re(#), Mi, Fa(#), Sol(#), La(#), Si
As the space between Mi and Fa (E and F) and Si and Do (B and C) is half a tone, we use (as far as I know) the following chord.

I know what the issue is, I could try to seek the code and propose a PR, but is my first time contributing on a js project, maybe a regular contributtor could issue a pr faster.

Thank you!

**Comment by martijnversluis** [comment]
Hey @hkfuertes . Thanks for reaching out!

I think `normalize()` is your friend here. It replaces all "illogical" variants by their logical counterpart. You can replace line 6 with:

```js
return parsed?.useModifier('#').toChordSolfegeString("c").normalize();
```

Please let me know if that solves your issue 👍
