### ISSUE TITLE
song::serialize

### ISSUE THREAD

**Issue by kahunacohen** [martijnversluis/ChordSheetJS#131]
Hi, Great package! Thanks for it.

I have a use-case which is saving the parsed song to a db in JSON format so that I can index on meta data, eg. title, capo etc instead of saving in chordpro, parsing on the server and extracting out meta data into separate db fields.

I don't see a public method to do this. Am I missing something?  It would be easy enough to serialize/deserialize just the static properties, but of course the methods would be problematic without some tinkering and/or using a third-party library. Thoughts? I'm happy to issue PRs if needed.

**Comment by martijnversluis** [comment]
Hey @kahunacohen,

Thanks for your question.

If your main concern is retrieving the song metadata, this should be quite easy. The `Song` object has a getter called `metaData` which returns a plain object containing all metadata, see: https://github.com/martijnversluis/ChordSheetJS#Song+metaData. You should be able to convert this object to JSON without any conversion logic:

```js
const json = JSON.stringify(song.metaData);
```

The only gotcha is that the value of a key-value pair in this object _might_ be an array when multiple values have been declared:

```
{artist: The Chordies}
{composer: John}
{composer: Will}
```

The `metaData` object will look like:

```js
{
  artist: 'The Chordies',
  composer: ['John', 'Will']
}
```

If you need more data, the [API docs for `Song`](https://github.com/martijnversluis/ChordSheetJS#song) should be helpful, as this lists the public attributes that will always exist on a `Song` object, at least within one major release.

Please let me know if this helpful, or if you need more info.

**Comment by kahunacohen** [comment]
Yeah the main issue is that instead of saving the chordpro text to the db, I'd rather save a datastructure, like the lines and the meta data and have the client parse it back to either songpro or song text. My understanding is that you need a song instance to be able to parse to either one.

Also you say directives like {capo: 2} etc are supported, and I see them in the metadata but the formatters are not rendering them. Do I have to create my own formatter or extend existing ones to get these to render?

**Comment by elvinrejimone** [comment]
Hey, How can I convert the Entire Song to a JSON Object and back. I tried to convert the Song object data to String and then back to Object but after that it is not working.

**Comment by martijnversluis** [comment]
@kahunacohen @elvinrejimone To be able to serialize and deserialize a complete song, serialization should probably be implemented for `Song`, `Line`, `Tag` and `ChordLyricsPair`. I can put that on the roadmap, I'd have to check when to make time to implement it.

**Comment by kahunacohen** [comment]
I would also be interested in possibly implementing this.
