### ISSUE TITLE
Best way to store in DB

### ISSUE THREAD

**Issue by aonghas** [martijnversluis/ChordSheetJS#1381]
Hi there,

Not really an issue but a question. Is there any benefit in storing the serialized chordsheetjs object in a database or is there no additional data that Chordpro format could already store?

Thanks

**Comment by martijnversluis** [comment]
Hey @aonghas. Thanks for reaching out!

The parses and formatter are designed to be lossless, so indeed Chordpro should be able to contain all information. However, if you notice any loss or accidental change of information you should definitely submit an issue! 👍

**Comment by aonghas** [comment]
Awesome thanks, and great work!
