### ISSUE TITLE
Exceptions while parsing meta tags

### ISSUE THREAD

**Issue by ldelia** [martijnversluis/ChordSheetJS#161]
When using chord pro format, it would be great to handle a custom exception when it is not possible to parse a meta tag.
For example, the user may write (incorrectly) something like:
{ title: Let it be}

(Note the ' ' before title)

**Comment by martijnversluis** [comment]
Fair point, I noticed ChordFiddle even crashes on your example sheet 😨. It should maybe not even raise on the whitespace, only return a warning.

I'll check if I have time soon to check this.

**Comment by martijnversluis** [comment]
Hey @ldelia ! I was checking the issue list and saw this one. Yesterday I published version [4.1.0](https://github.com/martijnversluis/ChordSheetJS/releases/tag/v4.1.0), I noticed this bug has been solved in that version.
