### ISSUE TITLE
reset the transposed sheet to original key 

### ISSUE THREAD

**Issue by ashish-ch-98** [martijnversluis/ChordSheetJS#167]
How can I reset the chord sheet to the original key after performing transpose function several times?

**Comment by martijnversluis** [comment]
Hi @ashish-ch-98. Thanks for your question. I'm not sure what you mean though:

- are you using [ChordFiddle](https://martijnversluis.github.io/ChordFiddle/) and do you want to reset the chord sheet to the initial key? That is not a feature at the moment. 
- are you using a combination of [ChordSheetJS](https://github.com/martijnversluis/ChordSheetJS) and [ChordJS](https://github.com/martijnversluis/ChordJS) and do you want to reset the chord sheet to the initial key? I could think of two solutions:
  - store multiple versions of the chord sheet in memory, at least the first one
  - keep track of how many steps the chord sheet has been transposed. For example, if the current chord sheet is netto transposed +4, you can reset the chords with `chord.transpose(-4)`

Please let me know if this answers your question.

**Comment by ashish-ch-98** [comment]
Thank you for your help. 

I am using a combination of ChordSheetJS and ChordJS. I put a reset button which should be transposing the chord sheet to the initial key.  I executed it using react hooks. For some transpose operations using up and down buttons, the reset function worked fine but after a while, it starts transposing to a key near to the new transposed key.

Here is my code for reset function: 

```
const [count, setCount] = useState(0)

function reset(){
   setKey(key.transpose(-count))
    song.lines.forEach(line => {
      line.items.forEach(item => {
        let chord = Chord.parse(item.chords)
        if(chord){
          chord = chord.transpose(count)
          item.chords = chord
        }
      })
    })
  }
```

**Comment by martijnversluis** [comment]
Nice @ashish-ch-98 !
