### ISSUE TITLE
ChordProParser: unspaced chords will cause issues

### ISSUE THREAD

**Issue by Glidias** [martijnversluis/ChordSheetJS#252]
`[Fsus4][F]`

Also, unclosed square brackets will cause issues but i think that is fine.

`[Fsus4] [F]` , cleanup add space in between is okay.

Is this much of an issue?

**Comment by martijnversluis** [comment]
Hey @Glidias ! Thanks for reporting this issue 👍 

I just published version [4.1.0](https://github.com/martijnversluis/ChordSheetJS/releases/tag/v4.1.0) which fixes this bug.
