### ISSUE TITLE
Chord diagrams without lyrics associated, for example on Intro line.

### ISSUE THREAD

**Issue by gmguzzo** [martijnversluis/ChordSheetJS#281]
I think there should be a easy way to display chords without lyrics associated to it, like in an introduction or bridge. Can you guide me through that? Is that something that is already supported or needs implementation? Thanks in advance.

**Comment by martijnversluis** [comment]
Hi @gmguzzo,

Sorry for keeping you waiting on this issue. Do you mean a chord pro sheet?

I mainly use something like below:

```
Intro:

[| ][A][ | ][D/F#][ | ][E/G#][ | ][A][ |]
[| ][A][ | ][D/F#][ | ][E/G#][ | ][A][ |]

Bridge:

[| ][A/C#][ | ][D][ | ][E][ | ][F#m][ |]
[| ][A/C#][ | ][D][ | ][E][ | ][F#m][ |]
```

See also ChordFiddle how this gets rendered: https://martijnversluis.github.io/ChordFiddle/#chord_sheet=JIOwLgTg9gXAUHA2gHwAQF1EEFOrZgEQHoAxAYl30QFEiBxCxPDbS9JKnJq48yl2g36YuednABCEAJYATAOYBTeBxZYiAYUbNCwmnvIBbNqpGbtPPdQNlj3dEA&preview=text
