### ISSUE TITLE
Using vertical bar ("|") in ChordPro song sheet

### ISSUE THREAD

**Issue by daysm** [martijnversluis/ChordSheetJS#297]
Is it possible to use a vertical bar in a ChordPro song sheet?

Currently I get the following error:
`SyntaxError: Expected "#", "%{", "[", "\\", "\n", "\r", "]", "{", "}", [^|[\]\\{}%#\r\n], end of input, or space but "|" found.`

I would like to use the vertical bar to indicate repetitions:
`|: Let it be :|`

**Comment by martijnversluis** [comment]
Hi!

Thanks for using ChordSheetJS and for submitting your issue!

The fastest solution is to use backslashes, which escape the `|` as special character:

    \|: Let it be :\|

I will check if I can simplify though, because outside of a `%{}` expression a `|` should not have any special meaning.

**Comment by martijnversluis** [comment]
I just released [`4.2.0`](https://github.com/martijnversluis/ChordSheetJS/releases/tag/v4.2.0) that allows unescaped `|` characters outside of meta expressions 👍

**Comment by daysm** [comment]
Amazing, thanks!
