### ISSUE TITLE
[Feature request] Inline chords

### ISSUE THREAD

**Issue by artutra** [martijnversluis/ChordSheetJS#30]
What about a inline chord notation? Like:
```
Intro: [[C]] [[Am]]
[C]Som[G]e random lyrics
```
So it will be rendered this way:
> Intro: **C** **Am**
>           **C**  **G**
> Some random lyrics

**Comment by martijnversluis** [comment]
@artutra Would you know any library or software that currently supports that "double bracket" notation?

**Comment by artutra** [comment]
Thanks for the quick response!
Sorry, I dont know of any library that supports this notation. It's just a suggestion that I think would make the notation more customizable.
I made a simple website for guitar tabs once (which already shut down) and there were many tabs with chords in line. So i had to make this little modification in chordpro notation.
And with `[Intro: ][C] [Am]` it would render an unnecessary blank line

**Comment by martijnversluis** [comment]
My goal for this library is to stick to the ChordPro specs. You are right though in saying a line having only chords (content between [ ] ) should not have a blank line below it, unless the blank line exists in the ChordPro source.

I'm going to add it to the project board and will probably release a patch for it soon.

Thanks again for your feedback!

**Comment by martijnversluis** [comment]
@artutra I fixed the "extra blank line" issue. I released [patch version 1.5.3](https://github.com/martijnversluis/ChordSheetJS/releases/tag/v1.5.3). I also updated [ChordFiddle](https://martijnversluis.github.io/ChordFiddle) to use this version.

**Comment by artutra** [comment]
Thanks man!
