### ISSUE TITLE
Allow running in the browser without NodeJS

### ISSUE THREAD

**Issue by kiritnarain** [martijnversluis/ChordSheetJS#311]
It would be great if this library could be added via a script tag.

**Comment by martijnversluis** [comment]
Great remark @kiritnarain!

I'm planning for adding a `browserify`'d package to the releases, to allow downloading a ZIP and using the library without a package manager nor build tool.

In the meantime you can use wzrd.in for this:

```html
<script src="https://wzrd.in/standalone/chordsheetjs@4.3.1"></script>
```

**Comment by topse** [comment]
I would be interested too... the given link for 4.3.1 does not work anymore :-/

**Comment by martijnversluis** [comment]
Good news! As of now, a standalone `bundle.js` file is generated for every release. Please see the dedicated section in the README: https://github.com/martijnversluis/ChordSheetJS#standalone-bundle-file

**Comment by topse** [comment]
so great!!! I you like I am gonna give you an update if my project starts to be interesting :-)

**Comment by martijnversluis** [comment]
Definitely, curious to see what you're building!

**Comment by topse** [comment]
Hi,
I still have problems... I took an small ChordPro example from the official website and made the following test-Website:

index.html (please add bundle.js next to it):
```
<!DOCTYPE html>
<html>
	<head>
		<script src="bundle.js"></script>
		<script>

			const doConversion = (formatterName) => {
				try {
					const chordSheet = '# A simple ChordPro song.\n\n{title: Swing Low Sweet Chariot}\n\n{start_of_chorus}\nSwing [D]low, sweet [G]chari[D]ot,\nComin’ for tocarry me [A7]home.\nSwing [D7]low, sweet [G]chari[D]ot,\nComin’ for to [A7]carry me [D]home.\n{end_of_chorus}\n\nI [D]looked overJordan, and [G]what did I [D]see,\nComin’ for to carry me [A7]home.\nA [D]band of angels [G]comin’ after [D]me,\nComin’ for to[A7]carry me [D]home.\n\n{comment: Chorus}';
					
					const parser = new ChordSheetJS.ChordProParser();
					const song = parser.parse(chordSheet);

					let formatter;
					switch(formatterName) {
						case 'TextFormatter':
							formatter = new ChordSheetJS.TextFormatter();
							break;
						case 'HtmlTableFormatter':
							formatter = new ChordSheetJS.HtmlTableFormatter();
							break;
						case 'HtmlDivFormatter':
							formatter = new ChordSheetJS.HtmlDivFormatter();
							break;
						case 'ChordProFormatter':
							formatter = new ChordSheetJS.ChordProFormatter();
							break;
					}
					const disp = formatter.format(song);
					
					document.getElementById("root").innerHTML = disp;
				} catch(err) {
					document.getElementById("root").innerHTML = err;
				}
			}

			window.addEventListener('load', () => {
				document.body.addEventListener('change', function (e) {
					doConversion(e.target.value);
				});
			});
		</script>
	</head>
	<body>
	<input type="radio" name="formatterType" value="TextFormatter" /> TextFormatter<br/>
	<input type="radio" name="formatterType" value="HtmlTableFormatter"/> HtmlTableFormatter<br/>
	<input type="radio" name="formatterType" value="HtmlDivFormatter"/> HtmlDivFormatter<br/>
	<input type="radio" name="formatterType" value="ChordProFormatter"/> ChordProFormatter<br/>
	<div id="root" />
	</body>
</html>
```

Please have a looko for yourself: only the Table-Formatter seems to do something useful?

Best Regards,
Tobias

**Comment by martijnversluis** [comment]
@topse I think your issue is caused by #481, which has been solved in version `6.3.0`. Could you test your app with the [newest bundle](https://github.com/martijnversluis/ChordSheetJS/releases/tag/v6.3.0) and let me know if it solves the issue?

**Comment by topse** [comment]
👍 Thanks!! Really appreciate your work!

**Comment by spiffylogic** [comment]
> Good news! As of now, a standalone `bundle.js` file is generated for every release. Please see the dedicated section in the README: https://github.com/martijnversluis/ChordSheetJS#standalone-bundle-file

@martijnversluis can you explain how this `bundle.js` is generated from source? (for someone new to JS who wants to fork your repo 😉 ) Thanks!

**Comment by martijnversluis** [comment]
> > Good news! As of now, a standalone `bundle.js` file is generated for every release. Please see the dedicated section in the README: [martijnversluis/ChordSheetJS#standalone-bundle-file](https://github.com/martijnversluis/ChordSheetJS#standalone-bundle-file)
> 
> @martijnversluis can you explain how this `bundle.js` is generated from source? (for someone new to JS who wants to fork your repo 😉 ) Thanks!

Hey @spiffylogic. Sure I can!

There is a [`release` workflow](https://github.com/martijnversluis/ChordSheetJS/blob/master/.github/workflows/release.yml) that triggers when a tag matching `v*.*.*` is pushed. It runs:

- a git checkout to get the files
- `yarn install` to install the required Node modules
- `yarn build` which performs some code generation and in the end [uses](https://github.com/martijnversluis/ChordSheetJS/blob/master/package.json#L63) a tool called [Browserify](https://browserify.org/) to generate the standalone bundle
- uses `cat` to verify the bundle file is generated
- runs the `softprops/action-gh-release` workflow to create a GitHub release  with the bundle file attached.

...and that's it! ✨ Please let me know if this properly answer your question 👍
