### ISSUE TITLE
HtmlTableFormatter table formatter only return chord with lyrics.

### ISSUE THREAD

**Issue by alexaung** [martijnversluis/ChordSheetJS#421]
HtmlTableFormatter only return chord without lyric. I am using chordsheetjs": "^5.1.2"
By the way, I am using tailwind css. 

    const getChordSheet = (value) => {
    value = `
    {title: Let it be}
    {subtitle: ChordSheetJS example version}
    {Chorus}

    Let it [Am]be, let it [C/G]be, let it [F]be, let it [C]be
    [C]Whisper words of [G]wisdom, let it [F]be [C/E] [Dm] [C]`.substring(1);

    
    //setFieldValue('lyric', value);
    const parser = new ChordSheetJS.ChordProParser();
    const song = parser.parse(value.substring(1));

    const formatter = new ChordSheetJS.HtmlTableFormatter();
    const chordSheet = formatter.format(song);
    console.log(chordSheet);
    return chordSheet;
    //setChordSheet(chordSheet);
    }`

Here is html output
    `<h2>ChordSheetJS example version</h2><div class="chord-sheet"><div class="paragraph"><table class="row"></table></div><div class="paragraph"><table class="row"><tr><td class="chord"></td><td class="chord">Am</td><td class="chord">C/G</td><td class="chord">F</td><td class="chord">C</td></tr></table><table class="row"><tr><td class="chord">C</td><td class="chord">G</td><td class="chord">F</td><td class="chord">C/E</td><td class="chord">Dm</td><td class="chord">C</td></tr></table></div></div>
`

**Comment by martijnversluis** [comment]
Hi @alexaung. Thanks for reporting your issue.

I must say it's a strange issue, so far I haven't been able to reproduce the output you got.

To validate I created [this PR](https://github.com/martijnversluis/ChordSheetJS/pull/429). It validates the HTML output for your chordpro sheet. I got correct output that did include lyrics.

There is one thing though: I see you declare the chordpro sheet with:

    `(chord pro source...)`.substring(1)

and then call `.substring(1)` in `parser.parse(value.substring(1))`. That second call will strip off the first `{` character which produces invalid chordpro and will return unexpected results. I also added a test case for validation. That did fail, but in an expected way: it parsed `title: Let it be}` as lyrics. The lyrics were all present in the HTML output though.

Could you first check the output after removing the duplicate `.substring(1)` call?

If that does not solve it, could you point to a project/branch on GitHub/Gitlab that shows the setup?

**Comment by martijnversluis** [comment]
This is the test output for the second test (with the duplicate `.substring(1)`):

![image](https://user-images.githubusercontent.com/1219904/149016831-8dfe9e56-98b0-4b22-a54e-57c0d4664572.png)

**Comment by alexaung** [comment]
Any idea?

**Comment by martijnversluis** [comment]
Ah sorry @alexaung, didn't realise this one was still pending.

I just figured out the problem: inside the template I'm checking the constructor name of items to figure out how to render them. However, due to the build process the constructor name changes:

![image](https://user-images.githubusercontent.com/1219904/151705270-f9e40b79-fa4d-4935-be03-5b0f14229634.png)

I gotta figure out a different way to check renderable items. Keep you posted!

**Comment by martijnversluis** [comment]
@alexaung I solved the issue. If you upgrade to `5.1.3` the table version will render correctly 👍
