### ISSUE TITLE
ChordSheetJs v5.1.2 and react 17.0.2 got error

### ISSUE THREAD

**Issue by alexaung** [martijnversluis/ChordSheetJS#426]
I got the following error after I import import ChordSheetJS from "chordsheetjs";

Compiled with problems:X

ERROR in ./node_modules/handlebars/lib/index.js 15:11-24

Module not found: Error: Can't resolve 'fs' in '/Users/zzzzz/Development/chordsheep/node_modules/handlebars/lib'

**Comment by martijnversluis** [comment]
Hey @alexaung. Thanks for reporting your issue. 

Could you maybe describe your build setup, or link your project on GitHub/Gitlab? That could help me trying to figure out your error.

**Comment by alexaung** [comment]
It is very simple, I just create the react app and install chordsheetjs and then import it. I did nothing but I can't build or run the app.

npx create-react-app my-chrodsheet
cd my-chrodsheet
yarn start
yarn add chordsheetjs

App.js

    
    import React, { useState } from "react";
    import ChordSheetJS from "chordsheetjs";
    import './App.css';

    function App() {
      return (
         <div className="App">
      
         </div>
       );
     }

     export default App;

**Comment by alexaung** [comment]
npx create-react-app my-app
cd my-app
yarn start
yarn add chordsheetjs
import in app.js

That all I did but could not build.

But I create the project with vitejs, this error is gone.

**Comment by danielsarin** [comment]
I had the same issue with Next.js. I think it's related to this https://github.com/handlebars-lang/handlebars.js/issues/1174.

I fixed it by adding a custom webpack config:

```
module.exports = {
  webpack: (config) => {
    config.resolve.alias = {
      ...config.resolve.alias,
      handlebars: 'handlebars/dist/handlebars.min.js'
    };
    return config;
  }
};
```
