### ISSUE TITLE
error occurred found \n

### ISSUE THREAD

**Issue by alexaung** [martijnversluis/ChordSheetJS#446]
We are facing a-lot of issue with \n error as follow. We wrote the lyrics in notepad and copy it to reactjs textarea. We can't find the \n. and we can't replace it because we need line break. May I know how to overcome those issue.

expected: (12) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]
found: "\n"
location: {start: {…}, end: {…}}
message: "Expected \"\\\\\", \"]\", or [^\\]\\r\\n] but \"\\n\" found."
name: "SyntaxError"
stack: "SyntaxError: Expected \"\\\\\", \"]\", or [^\\]\\r\\n] but \"\\n\" found.\n    at by (https://admin.myanmargita.com/assets/vendor.1d2dc762.js:2764:855)\n    at Object.A2e [as parse] (https://admin.myanmargita.com/assets/vendor.1d2dc762.js:2764:7978)\n    at u.value (https://admin.myanmargita.com/assets/vendor.1d2dc762.js:2777:15001)\n    at i (https://admin.myanmargita.com/assets/index.263c2769.js:249:3517)\n    at Ue (https://admin.myanmargita.com/assets/index.263c2769.js:249:4686)\n    at iT (https://admin.myanmargita.com/assets/vendor.1d2dc762.js:30:53022)\n    at gG (https://admin.myanmargita.com/assets/vendor.1d2dc762.js:34:8799)\n    at fG (https://admin.myanmargita.com/assets/vendor.1d2dc762.js:34:950)\n    at nZ (https://admin.myanmargita.com/assets/vendor.1d2dc762.js:34:878)\n    at og (https://admin.myanmargita.com/assets/vendor.1d2dc762.js:34:731)"
[[Prototype]]: Error 

Please find the reproducible code here 
[https://github.com/alexaung/my_chordsheep](Github example)

**Comment by martijnversluis** [comment]
Hey @alexaung,

Thanks for reporting your issue. 

The big downside of using a PegParser is that it is kinda strict, hard to make it more forgiving, and hard to get a descriptive error.

Let me clarify why the error occurs. Your chord sheet is as follows:

```
 1. 
 2. Intro : Dbm A B A B Dbm A B Gb Dbm Dbm
 3. [Dbm]ငါ့နေ့ရက်များ . . . [A]အတ္တရဲ့ပြေးလမ်းပေါ် တစ်ယောက်ထဲ . . .[Dbm]တရွေ့ရွေ့နဲ့ဖြတ်သန်း . . .[A]နေဝင်ညများကူးဖြတ်လိုက်စမ်း . . .[Dbm]
 4. [Dbm]ရိုက်ခတ်များ . . .[A]ပစ်လွှတ်တဲ့မြားသွားတွေလိုပဲ[Dbm]. . . [Dbm]ရင်မှာစူးနစ်လို့နေခဲ့ . . . အဆိပ်တတ်ခဲ့ပြီ[A]မင်းတွေ့လား . . .[Dbm]
 5. *[B]အတ္တရဲ့ရိုက်ချက်များ/ပြေးလမ်းက . . . [A](ငါ)လွယ်လွယ်မေ့ထားမလား/ထွက်သွားမလား . . .
 6. [B]သွေးအေးစွာ အရှုံးပေးမလား . . .[Ab]နောက်လှည့်ပြန်မလား . . .
 7. [Dbm]ဒဏ်ရာများ . . .[A]မေ့ပစ်နိုင်လား . . . [E][B][AB](အနိုင်ယူချင်တဲ့ငါစိတ်များ) . . .[A][E][Dbm][B][B] [A][B]
 8.
 9. [Dbm]အတ္တညများ . . . [A]တစ်ခုခုတော့ မှားယွင်းနေမှာပဲ . . .
10. [Dbm]သွေးပျက်ရင်းဖြတ်သန်း . . .[A]နောက်ကအရိပ်တွေ လိုက်လို့လာခဲ့. . .[Dbm]
11. [Dbm]ငါစိတ်ဓါတ်များ . . .[A]တမြည့်မြည့်နဲ့ကျွမ်းတောက်လောင်နေခဲ့[Dbm
12. [Dbm]ငါဟာပြေးရင်းပြေးနေခဲ့ . . . တစ်နေ့နေ့ရောက်မယ်[A]မင်းကြည့်နေလိုက် . . .
13. [Dbm]တစ်နေ့နေ့တော့ရောက်မှာပဲ . . . 
14. Music & (Cho with Key F) FADE
```

The parser complains it finds a newline at line 11 column 68 (the end of the line, right after the `m`) where it expects `\\`, `]`, or `[^\]\r\n]`. You will find the closing `]` is missing for the `[Dbm]`

**Comment by alexaung** [comment]
@martijnversluis Sorry for mistake and your time. I looking at the root cause before posted on here. But somehow missed it.  Yes, it is user error. I need to find a way to tell them. Thanks.
