### ISSUE TITLE
OnSong parser

### ISSUE THREAD

**Issue by bkeepers** [martijnversluis/ChordSheetJS#458]
The [OnSong](https://onsongapp.com/docs/features/formats/onsong) format is loosely based on ChordPro, and after looking at it more closely over the last few days, I _really_ like it. It's more human-readable (no more `{` and `}`) and has a number of improvements, especially with regard to how chordsheets are typically structured ([metadata](https://www.onsongapp.com/docs/features/formats/onsong/metadata/), [sections](https://www.onsongapp.com/docs/features/formats/onsong/section/), and [Flow](https://www.onsongapp.com/docs/features/formats/onsong/metadata/flow/)).

I'm looking for a preferred format for https://github.com/bkeepers/chordbook (https://github.com/bkeepers/chordbook/pull/130) and would like to try OnSong.

Would you be open to accepting a Pull Request for an pegjs-based parser for OnSong?

**Comment by bkeepers** [comment]
Awesome, I'll get a PR open soon. I'm about 50% done with the grammar.

We'll have a lot to talk about. OnSong is basically a superset of both ChordPro and ChordSheet formats. The AST will need to be structured differently than ChordPro to get the `Flow` metatag to work. It might still be able to be deserialized into the same `Song` model, but there may need to be some modifications.

**Comment by mfuentesg** [comment]
Hey @martijnversluis do you know if this PR has been completed?

**Comment by bkeepers** [comment]
@mfuentesg Not yet, but for now I extracted this to its own package: https://github.com/chordbook/onsong

I'd love to see OnSong support get added to ChordSheetJS eventually, but it's not a priority for me right now.

**Comment by mfuentesg** [comment]
Thanks @bkeepers, great package btw
