### ISSUE TITLE
HtmlDivFormatter for ChordProParser is not properly aligned

### ISSUE THREAD

**Issue by alexaung** [martijnversluis/ChordSheetJS#473]
Hi,

I am using ChordProParser with HtmlTableFormatter. It working as expected. But it is not responsive on mobile because some line are longer than the mobile screen width. So I tried to use HtmlDivFormatter and it is not working as expected. It is go down for every single chop.

Please see my working example. 

[GitHub](https://github.com/alexaung/my_chordsheep)

**Comment by martijnversluis** [comment]
Hey @alexaung. Thanks for submitting your question.

The divved output indeed needs some basic css to work. The formatter has some styles built in which you can use: [a CSS string](https://github.com/martijnversluis/ChordSheetJS#HtmlDivFormatter.cssString) or [an object](https://github.com/martijnversluis/ChordSheetJS#htmldivformattercssobject--objectstring-objectstring-string) which you can use with React inline styles. As an alternative you can also look them up [in the source](https://github.com/martijnversluis/ChordSheetJS/blob/master/src/formatter/html_div_formatter.js#L10).

Please let know if this is helpful.

**Comment by alexaung** [comment]
Thanks @martijnversluis. I am using it in reactjs with tailwind css. Let me try will let you know.

**Comment by alexaung** [comment]
I used HtmlDivFormatter for responsive layout. Need to add following css

`.chord-sheet .paragraph .row {
  display: flex;
  flex-wrap: wrap;
}

 .chord-sheet .paragraph .row .column .lyrics {
   white-space: pre-wrap;      /* CSS3 */   
   white-space: -moz-pre-wrap; /* Firefox */    
   white-space: -pre-wrap;     /* Opera <7 */   
   white-space: -o-pre-wrap;   /* Opera 7 */    
   word-wrap: break-word;      /* IE */
}

.chord-sheet .paragraph .row .column .chord:after {
  content: " ";
}

.chord-sheet .paragraph .row .column .lyrics:after {
  content: " ";
}`

**Comment by vjousse** [comment]
Just for the record, I had to use the [Zero Width Space UTF8](https://en.wikipedia.org/wiki/Zero-width_space) character instead of just " " to make it work.

Thanks for the CSS example, could be helpful to have it somewhere in the documentation!

```css
.chord-sheet .paragraph .row .column .chord:after {
content: "\200b"; 
}

.chord-sheet .paragraph .row .column .lyrics:after {
content: "\200b";
}`
```
