### ISSUE TITLE
The formatter does not return the content of the song

### ISSUE THREAD

**Issue by Gonzalo2683** [martijnversluis/ChordSheetJS#481]
Hello, very interesting project, I have a question.

I have taken as an example the code that you have in the ChordSheetJS Fiddle repo, I am trying to raise/lower chord transport of a song.

I am using Parcel as a bundler for my tests.

I have debugged the code, and even before the formatter application, the values of the lines are already with the chords transported, when it goes through the formatter function I only receive the result:

```html
<div class="chord-sheet"></div>
```

Debug example:
![debug_ok](https://user-images.githubusercontent.com/1046320/163516119-9900831f-a471-4c23-8b39-c234e7824c39.png)

Result:
![formatter_result](https://user-images.githubusercontent.com/1046320/163516377-d37a019f-b2e0-4669-b8cd-a5a097197b75.png)

Code sample:
```html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <title>My First Parcel App</title>
  <link rel="stylesheet" href="styles.css" />
  <script type="module" src="app.js"></script>
</head>
<body>

<div style="border: 1px solid #0c645f">
  <button type="submit" id="up">Subir</button>
  <button type="submit" id="down">Bajar</button>
</div>
<div id="song"></div>
</body>
</html>

```
```js
import ChordSheetJS, { Chord } from "chordsheetjs";

const chordSheet = `
Let it [Am]be, let it [C/G]be, let it [F]be, let it [C]be
[C]Whisper words of [G]wisdom, let it [F]be [C/E] [Dm] [C]`.substring(1);

const upBtn = document.getElementById("up");
const downBtn = document.getElementById("down");
const songId = document.getElementById("song");

const processChord = (item, processor) => {
  if (item instanceof ChordSheetJS.ChordLyricsPair && item.chords) {
    const parsedChord = Chord.parse(item.chords);

    if (parsedChord) {
      const processedChordLyricsPair = item.clone();
      processedChordLyricsPair.chords = processor(parsedChord).toString();
      return processedChordLyricsPair;
    }
  }
  return item;
};

const transformSong = (song, processor) => {
  const processedSong = song.clone();

  processedSong.lines = song.lines.map((line) => {
    const processedLine = line.clone();
    processedLine.items = line.items.map((item) => {
      return processChord(item, processor);
    });
    return processedLine;
  });
  return processedSong;
};

const transformChordSheet = (chordSheet, processor) => {
  const song = new ChordSheetJS.ChordProParser().parse(chordSheet);
  const processedSong = transformSong(song, processor);
  const formatter = new ChordSheetJS.HtmlDivFormatter();
  return formatter.format(processedSong);
};

const transposeUp = (chordSheet) => {
  return transformChordSheet(chordSheet, (chord) => chord.transposeUp());
};

upBtn.addEventListener("click", function (el) {
  const result = transposeUp(chordSheet);
  setSong(result);
});

const setSong = (data) => {
  songId.innerHTML = data;
};
```

I've tried various formatters and get the same result, any ideas what might be going on?

**Comment by Gonzalo2683** [comment]
I don't know if it has anything to do with it, but the only difference I see on the fly is that the paragrap property has no elements in the transposed version.

Example,
The variable `transposedSheet` has only the transposed song
The `song` variable has the song parsed directly without transporting it

![diff](https://user-images.githubusercontent.com/1046320/163577373-5b3431fc-fca1-4ff6-a962-caf8ca5c1dda.png)

**Comment by martijnversluis** [comment]
Hey @Gonzalo2683. Thanks for reporting your issue.

Which version are you using. And do you, by chance, have a repo I can checkout? That would make it easier for me to try to reproduce and debug the issue.

Thanks!

**Comment by Gonzalo2683** [comment]
The debug details of the first two screenshots used the latest version available chordsheetjs@6.1.0
I am getting the same results from not having elements in the paragraphs property.

In the screenshots where I show the difference between the two song objects, use the same versions that you have in ChordFiddle, that is:
"chordjs": "^2.0.1",
"chordsheetjs": "^4.10.0"

I don't have a repo, but I'm going to create it for testing.

**Comment by Gonzalo2683** [comment]
The repo for test: @martijnversluis 
https://github.com/Gonzalo2683/chordsheetjs_test

**Comment by martijnversluis** [comment]
@Gonzalo2683 Thanks for your info and for setting up the repo. I did some investigation, it looks like a bug. 

The formatter is using the `paragraphs` property on `Song`, but the logging in your app shows `paragraphs` is empty after the song is transposed.

I'm gonna work on a test to prove the bug and on a resolution.

**Comment by martijnversluis** [comment]
Hey @Gonzalo2683. I managed to implement a fix for this. If you upgrade to `6.3.0` it works correctly.

This version also introduced the official supported method [`Song#mapItems`](https://github.com/martijnversluis/ChordSheetJS#Song+mapItems) which allows you to change the song. I'd recommend using that, because it's supported and tested.

Please let me know if there is still an issue.

**Comment by Gonzalo2683** [comment]
If it works correctly now, I tried it with the functions of the chordFiddle example, I'm going to take a look at Song#mapItems how it works.

Very grateful for the effort.

**Comment by Gonzalo2683** [comment]
Excelent...

![chordfiddle](https://user-images.githubusercontent.com/1046320/164113766-ad5323b2-32a5-469a-bf7e-c77a3775616c.gif)
