### ISSUE TITLE
Improve chord parsing in ChordSheetParser

### ISSUE THREAD

**Issue by martijnversluis** [martijnversluis/ChordSheetJS#482]
As concluded in [#461](https://github.com/martijnversluis/ChordSheetJS/pull/461#discussion_r811292944), the chord parsing format in `ChordSheetParser` is not inclusive enough and not consistent with how `Chord.parse` functions. The format should be extended to match all possible chords. If possible, it would be nice to have shared logic for recognising and parsing chords.

**Comment by paulrobertpine** [comment]
I'm not sure how he ChordProParser HtmlDivFormatter chooses how to make paragraphs. I have what I think are 2 identical formats but one is making paragraphs after every line and the other behaves what I would consider correctly.

**Comment by martijnversluis** [comment]
Hi @paulrobertpine,

Thanks for reaching out. I think what you're describing is different from this issue here. Would you mind creating a [new issue](https://github.com/martijnversluis/ChordSheetJS/issues/new/choose), also providing the code and chord sheet(s) you're using? I'll try if I can find a solution.
