### ISSUE TITLE
switchModifier() missing from Chord

### ISSUE THREAD

**Issue by paulrobertpine** [martijnversluis/ChordSheetJS#544]
Hi there, 

I think the switchModifier() function is missing. It doesn't work in my code and I don't see it as an available functions when I inspect the Chord object using this technique: https://flaviocopes.com/how-to-list-object-methods-javascript/

**Comment by martijnversluis** [comment]
Hey @paulrobertpine. Good remark, this function actually got removed quite a while ago because the function is non-deterministic. I failed, however to remove it from the README.
