### ISSUE TITLE
Error on new Version

### ISSUE THREAD

**Issue by lucastrod** [martijnversluis/ChordSheetJS#567]
I'm getting this issue after install v7.2

![image](https://user-images.githubusercontent.com/20687915/172687286-2350771d-3635-4984-bf26-af839290d42b.png)

although i'm trying to find an stable version to continue

**Comment by martijnversluis** [comment]
Thanks for reporting this @lucastrod! I added it to the [board](https://github.com/martijnversluis/ChordSheetJS/projects/1), I need to time to investigate it.

**Comment by martijnversluis** [comment]
@lucastrod Could you retry using version `7.3.1`?
