### ISSUE TITLE
Make normalisation on transpose optional

### ISSUE THREAD

**Issue by martijnversluis** [martijnversluis/ChordSheetJS#570]
As suggested by @paulrobertpine

**Comment by martijnversluis** [comment]
@paulrobertpine I published version `7.4.0` which makes the chord suffix normalisation optional when tranposing a song.

**Comment by paulrobertpine** [comment]
Thanks!

**Comment by paulrobertpine** [comment]
Can you please post an example of usage? I can't seem to get it to work (I thought it would be setSong(song.transposeUp(false) or just it does it by default)

**Comment by martijnversluis** [comment]
Yeah. `setSong(song.transposeUp())` should be ok, the normalisation is off by default.
