### ISSUE TITLE
Include meta directives in metadata

### ISSUE THREAD

**Issue by bkeepers** [martijnversluis/ChordSheetJS#594]
The [meta directive](https://chordpro.org/chordpro/directives-meta/) allows defining arbitrary metadata. 

```
{meta: name value}
```

It would be nice if the values were included in `song.metadata`

**Comment by bkeepers** [comment]
I am trying to use a custom meta tag (`{meta: media https://www.youtube.com/watch?v=dQw4w9WgXcQ}`)

Per the [spec](https://chordpro.org/chordpro/directives-meta/):

> Meta-data names can be chosen freely although single lowercase words like `artist` and `composer` are advised. It is left to the ChordPro file processing tools to do something sensible with the meta-data.

So I would expect anything declared with `meta` would be available in `song.metadata`.

**Comment by martijnversluis** [comment]
@bkeepers I just released [`v7.6.0`](https://github.com/martijnversluis/ChordSheetJS/releases/tag/v7.6.0) which resolves this issue.
