### ISSUE TITLE
A way to replicate/reuse a section without retyping?

### ISSUE THREAD

**Issue by jbree** [martijnversluis/ChordSheetJS#779]
I see the ChordPro {chorus} directive is not supported or planned. Is there a supported way to repeat a previously defined section?

Edit:
To add more context, I'm creating a ChordPro preview generator for VSCode using chordsheetjs to read the file in and generate HTML. Hoping to duplicate sections via directives in input, not using API.

**Comment by martijnversluis** [comment]
Hey @jbree. Thanks for reaching out, great question! 
So far that directive (or a similar one) is not supported, but it seems a great idea! I’ll add a ticket to the [board](https://github.com/martijnversluis/ChordSheetJS/projects/1#column-1347756)! You can watch it to stay updated 👍

**Comment by martijnversluis** [comment]
Hey @jbree 

I just released [`v7.14.0`](https://github.com/martijnversluis/ChordSheetJS/releases/tag/v7.14.0) which adds support for this. Please let me know if that's helpful 👍

**Comment by jbree** [comment]
This is great! Thanks!
