### ISSUE TITLE
Question: is https://github.com/bettermusic/ChordSheetJS the official repo now?

### ISSUE THREAD

**Issue by mfuentesg** [martijnversluis/ChordSheetJS#787]
I wonder if bettermusic fork is the official repository, since it has a lot of commits ahead of this one. :)

**Comment by martijnversluis** [comment]
Hey @mfuentesg. No, this repo is still the base. I also work on the bettermusic fork, and try to sync as much as possible. The Dependabot PRs however are unique per repository, so that makes quite a number of commits that is not shared between the repos.

**Comment by mfuentesg** [comment]
Oh cool, thanks @martijnversluis, btw, thanks for this awesome repo. I'm using it for a songbook app for my son :D
