### ISSUE TITLE
Question: is there a way to predict the "key" of a song?

### ISSUE THREAD

**Issue by mfuentesg** [martijnversluis/ChordSheetJS#788]
I was wondering if it is possible, since some features like, transpose depends on a previously defined key, predict the base key of a song.

**Comment by martijnversluis** [comment]
It should be possible to determine the key from the chords, but ChordSheetJS does not have such feature. Currently it just transposes by delta (number of semitones) if the key is not known.

**Comment by mfuentesg** [comment]
Got it, do you have some "backlog" for this project?

**Comment by martijnversluis** [comment]
I do, it’s a project board: https://github.com/martijnversluis/ChordSheetJS/projects/1
