### ISSUE TITLE
Types for TypeScript

### ISSUE THREAD

**Issue by adamsbloom** [martijnversluis/ChordSheetJS#80]
I'd like to volunteer to submit a TypeScript .d.ts file for your project to DefinitelyTyped.

**Comment by martijnversluis** [comment]
@adamsbloom Great, that would be cool! I haven’t done much in TypeScript, but do you need anything from me to get that working?

**Comment by adamsbloom** [comment]
For DefinitelyTyped, no, there's nothing to be done on your end. What would be better, however, would be to include the types in the main ChordSheetJS package in the first place. I can create a fork and send you a pull req, if you'd like.

**Comment by martijnversluis** [comment]
Seems like a good idea!. I'm interested in TypeScript, so I might eventually add it, but that's currently not my focus.

Thanks in advance for this contribution! 👍
