### ISSUE TITLE
parse a lyrical chord without normalize. 

### ISSUE THREAD

**Issue by kzkpro** [martijnversluis/ChordSheetJS#838]
currently when i parse the lyrical songs Asus2 is printed as A2. is there a way to print it as it is? 

`    const parser = new ChordSheetJS.ChordsOverWordsParser();`
`      const song = parser.parse(chordSheet);`
      
`      const formatter = new ChordSheetJS.HtmlTableFormatter();`
`      const lyrics = formatter.format(song);`

Thanks!

**Comment by martijnversluis** [comment]
Hey @kzkpro. Thanks for reaching out. I don't think it's possible at the moment. However, it's a valid use case and relatively easy to implement. I'll try to add this in the next couple of days.

**Comment by martijnversluis** [comment]
@kzkpro I just released `v7.17.0`, which adds a `normalizeChords` option to the formatters. When setting that to `false`, chords are rendered using their original suffix. 👍 

Cheers!

**Comment by kzkpro** [comment]
Thanks @martijnversluis !
