### ISSUE TITLE
Simple html example that displays tab with custom CSS

### ISSUE THREAD

**Issue by eplebel** [martijnversluis/ChordSheetJS#853]
This looks amazing, thanks for your great work.

I'm looking for a simple html example that uses your ChordSheetJS functions to display chord sheets using modified CSS for some of the elements (e.g., chords, lyrics, etc.).  (index.html, index.js, and styles.css?)

I tried duplicating and modifying several examples I found online (your own ChordFiddle app, https://codesandbox.io/s/song-book-vetfk ,  https://codepen.io/rrherr/pen/qByemmN ) but couldn't get any to work.  I also read #398 .   

Any suggestions would be greatly appreciated.

**Edit:** Perhaps this is not possible, but if it is, it would help make your amazing work accessible to a much larger group of non-developers who may only have a surface-level understanding of JS (e.g., prototype designers, hobbyist programmers, etc.)

**Comment by eplebel** [comment]
I got it working with a bit more tinkering.  I plan on posting my working example (index.html, index.js, and styles.css) somewhere and linking here in case you're interested. Thanks again for your amazing library.

**Comment by eplebel** [comment]
Link to simple html example that parses a UG tab (index.html, styles.css, and index.js): https://etiennelebel.com/jb-chordsheetjs/index.html

Also available at a .zip file here: https://etiennelebel.com/jb-chordsheetjs/index.zip

Hope this can help a larger group of people use your useful library.

**Comment by martijnversluis** [comment]
Nice @eplebel, thanks for publishing this 👍
