### ISSUE TITLE
Support Chinese Character

### ISSUE THREAD

**Issue by mcdugray** [martijnversluis/ChordSheetJS#86]
The lyric and chord position is not matched in chinese character, please check
![image](https://user-images.githubusercontent.com/7552647/52685139-a4959b00-2f83-11e9-993f-a113d7761302.png)

**Comment by martijnversluis** [comment]
Hi @mcdugray,

Thanks for submitting your issue.

Although not specifically documented, the output of the ‘TextFormatter’ should always be rendered using a monospace font, because it uses spaces to align chords and lyrics. 

If you would like to use a non-monospace font, you can use one of the HTML formatters, assuming you are currently using ‘TextFormatter’.

Please let me know if this solves your problem.

**Comment by mcdugray** [comment]
Dear Mention 
As we put it in react native, the html formatter is not compatible? So do you have suggestion or u can enhance the existing program to support Chinese character 
regardsraymond

傳送自 Android 上的 Yahoo Mail 
 
  在 2019 年 2月 月 13 日 週三，時間： 1:43 下午，Martijn Versluis<notifications@github.com>寫道：   
Hi @mcdugray,

Thanks for submitting your issue.

Although not specifically documented, the output of the ‘TextFormatter’ should always be rendered using a monospace font, because it uses spaces to align chords and lyrics.

If you would like to use a non-monospace font, you can use one of the HTML formatters, assuming you are currently using ‘TextFormatter’.

Please let me know if this solves your problem.

**Comment by martijnversluis** [comment]
Hi @mcdugray,

As `TextFormatter` uses spaces for alignment it always requires a monospace font, not only for Chinese characters.

I think you have a few options:

- use a [monospace font](https://en.wikipedia.org/wiki/Monospaced_font) to display the `TextFormatter` output
- use one of the HTML formatters and display the HTML using a [React Native webview](https://aboutreact.com/react-native-load-local-html-file-in-webview/)
- create your own React Native component to render the parsed song. Get some inspiration from [`HtmlDivFormatter`](https://github.com/martijnversluis/ChordSheetJS/blob/master/src/formatter/html_div_formatter.js)
