### ISSUE TITLE
ChordSheetJS.HtmlTableFormatter({ normalizeChords: false }) creates extra spaces between lyrics words.

### ISSUE THREAD

**Issue by MeterKishor** [martijnversluis/ChordSheetJS#875]
when normalizeChords:false is passed to HtmlTableFormatter. it adds extra space between words. here's codepen link : [https://codepen.io/meterkishor/pen/wvYwJNE](https://codepen.io/meterkishor/pen/wvYwJNE)
Thanks!

**Comment by martijnversluis** [comment]
Hey @MeterKishor,

Thanks for reaching out! When inspecting the generated table, you can see some spacing between the table cells:

<img width="215" alt="image" src="https://user-images.githubusercontent.com/1219904/236668467-bea3cdc3-ad46-44fa-9391-0de6ff8e2265.png">

The browser adds some default spacing between the cell borders:

<img width="454" alt="image" src="https://user-images.githubusercontent.com/1219904/236668502-7c617755-cc50-45dc-8346-ea45d2442825.png">

and there is a default padding within the cell of `1px`:

![image](https://user-images.githubusercontent.com/1219904/236668573-e826faf4-ec88-4fdf-88d8-4b55d0edb96e.png)

The spacing is gone when using CSS to remove the border spacing and cell padding. I created a fork of your Codepen with the CSS applied: https://codepen.io/martijnversluis/pen/poxaNdg. 

Please let me know if that solves your issue.

Cheers!

**Comment by MercierCorentin** [comment]
On your Codepen, there are bonded word that should be seperated by a space:
![image](https://github.com/martijnversluis/ChordSheetJS/assets/46066895/2f38977e-dbc7-4eed-b394-1804c10c4e6c)

How can we have both plain word without space and unbonded words when there is a space ?

**Comment by davehell** [comment]
@MercierCorentin look at https://github.com/martijnversluis/ChordSheetJS/issues/473#issuecomment-1542742974

You need to add space afref the lyrics. Minimal example for HtmlTableFormatter is:
`
td {
  padding: 0;
}
.chord:after,
.lyrics:after {
  content: '\200b';
}
`
