### ISSUE TITLE
Get only the lyrics of a song

### ISSUE THREAD

**Issue by mmdfmateus** [martijnversluis/ChordSheetJS#908]
Hi, really glad to have found this, is there an easy (or any at all) to get only the lyrics of a parsed song?

Maybe something like iterating over every `ChordLyricsPair` and joining `.lyrics` of each one? 
I had a hard time trying this, any thoughts?

**Comment by martijnversluis** [comment]
Hey @mmdfmateus. Thanks for reaching out.

You're spot with your suggestion! I created a codepen that shows how to get the lyrics: https://codepen.io/martijnversluis/pen/PoxPWQP

Please let me know if this answers your question properly 👍

**Comment by ianpogi5** [comment]
Sorry to revive this but I would also like to know how to do this. The codepen link is dead.

Preferably I would like to pass a parameter to the formatter:
```js
TextFormatter({ lyricsOnly: true })
```

Thank you very much for this project!
