### ISSUE TITLE
Could you please publish a new version to NPM?

### ISSUE THREAD

**Issue by nsndvd** [martijnversluis/ChordSheetJS#91]
I'm interested in a feature that is in your master, but unreleased on NPM (namely, divs wrapping chorus paragraphs in the HTML table formatter). Are you planning to release a new version with those changes?

**Comment by martijnversluis** [comment]
Hi @nsndvd,

Sorry for the confusion. All releases up to `2.8.1` have been published to NPM. However, when Travis publishes a release, only a tag is created in Github, not a release. I've updated the release info to mirror the NPM releases.

Thanks for noticing!

**Comment by nsndvd** [comment]
Hi, thanks for the quick response. 
Actually I am getting the package from NPM, and I am already working with version 2.8.1. Though the change I'm interested in is in one of the 40 commits that follow.
Should I take it that you are not going to publish a new release soon?
If not, I guess I'll find a way to take the change in locally. Thanks for the great work!

**Comment by martijnversluis** [comment]
Oh sorry, I looked up the wrong feature. I’ll try to publish everything unreleased tomorrow 👍

**Comment by nsndvd** [comment]
Awesome!

**Comment by martijnversluis** [comment]
@nsndvd I releases `2.9.0` to NPM! https://github.com/martijnversluis/ChordSheetJS/releases/tag/v2.9.0

**Comment by nsndvd** [comment]
Maybe it's me, but it looks weird. If I install it I get an empty package, only these files:
`LICENSE
README.md
package.json
README.hbs
package-lock.json`

How can I buy you a beer? You definitely deserve one.

**Comment by martijnversluis** [comment]
😞 Apparently my awesome automatic publish from CI doesn't always work.... I manually published `2.9.1`, could you try that one?

**Comment by nsndvd** [comment]
All files back where they belong, update working as expected! Charming! I
really want to buy you a beer!

**Comment by martijnversluis** [comment]
No problem, glad it’s working now! 👍

If you are interested in bying me a beer, you can always donate via https://paypal.me/martijnversluis 🍻
