### ISSUE TITLE
ultimate_guitar_parser using deprecated ChordSheetParser?

### ISSUE THREAD

**Issue by eplebel** [martijnversluis/ChordSheetJS#922]
I'm getting the warning "ChordSheetParser is deprecated, please use ChordsOverWordsParser. "

but i'm using the UltimateGuitarParser ( https://github.com/martijnversluis/ChordSheetJS/blob/master/src/parser/ultimate_guitar_parser.ts )
`const parser = new ChordSheetJS.UltimateGuitarParser();`

which itself appears to be using the deprecated ChordSheetParser (on line 2)
`import ChordSheetParser from './chord_sheet_parser';`

is this by design or am i perhaps misunderstanding something?

**Comment by martijnversluis** [comment]
Hey @eplebel! Thanks for reaching out 👍 

It's somewhat by design, `ChordSheetParser` is indeed deprecated. However, there are a few pending issues with it, and using it as a base for `UltimateGuitarParser` would also introduce those issues there. 

I'll take a look if there is an easy way to "hide" the deprecation warning for subclasses.

**Comment by eplebel** [comment]
OK thanks for the update.

Is there any chance that this deprecated ChordSheetParser issue with the UltimateGuitarParser could be causing this other issue I'm observing whereby Verse and Chorus (only) section labels are incorrectly omitted if they're lower case.

That is, non-verse & non-chorus section names correctly appear (whether in lowercase or upper case) whereas verse and chorus section names *only* appear in upper case.  Examples:
- Correctly appear:
  - "[Intro]" or "[INTRO]"
  - "[Bridge]" or "[BRIDGE]"
  - "[VERSE 1]"
  - "[CHORUS]"
- Missing/do not appear:
  - "[Verse 1]"
  - "[Chorus]" 

The issue does NOT occur with the Chord pro parser (const parser = new ChordSheetJS.ChordProParser(); )

**Comment by martijnversluis** [comment]
@eplebel I just published `v7.17.3`, the deprecation warning should now be gone. 👍
