### ISSUE TITLE
Improve html formatter

### ISSUE THREAD

**Issue by mfuentesg** [martijnversluis/ChordSheetJS#934]
Hey @martijnversluis before all, thanks for this amazing library!

I'm working in a chord library app, and, I wanted to customize some parts of the HTMLFormatter, reusing some of the utilities that have built (i.e `isEvaluatable`, `fontStyleTag`), but, those functions are not exported.

I built a react component based on the `templates/html_div_formatter.ts` copying almost everything from your it.

I was thinking how to improve formatter API in order to make it a bit more easier to customize instead of duplicate your formatter examples.

Have a nice day/evening/night!

**Comment by martijnversluis** [comment]
Hey @mfuentesg,

Thanks for reaching out!

I think it would make sense to export these utility functions in a file like `formatter/html_formatter/utilities`. I'll add your request to the [project board](https://github.com/martijnversluis/ChordSheetJS/projects/1).

**Comment by martijnversluis** [comment]
@mfuentesg I published `v8.1.0` 👍
