### ISSUE TITLE
Add support for parsing minus sign (-)

### ISSUE THREAD

**Issue by DonkeyBear** [martijnversluis/ChordSheetJS#952]
Make `Chord.parse()` can parse something like Dm7-5 (another notation for Dm7b5).

**Comment by martijnversluis** [comment]
Hey @DonkeyBear,

Thanks for reaching out!

Your request makes sense, I'm adding it to the [project board](https://github.com/martijnversluis/ChordSheetJS/projects/1)!

**Comment by martijnversluis** [comment]
@DonkeyBear I just published `v7.18.0`, that should resolve the bug! 👍
