### ISSUE TITLE
support of chordpro v6?

### ISSUE THREAD

**Issue by mfuentesg** [martijnversluis/ChordSheetJS#966]
Is there any plan to support chordpro v6?

**Comment by martijnversluis** [comment]
Hey @mfuentesg,

No plans yet, must admit I totally missed this release. I’m gonna check out what I think should be supported at minimum. 

Are there any specific features you’d like to see supported? 🤩

**Comment by martijnversluis** [comment]
For reference, this is the V6 changelog: https://www.chordpro.org/chordpro/chordpro6-relnotes/

**Comment by mfuentesg** [comment]
Nothing special, I just wanted to mention the new chordpro version 😄 in order to be considered in the project's roadmap

**Comment by martijnversluis** [comment]
@mfuentesg Thanks for your input! 

I have created issues for the features that are likely to be supported within a reasonable timeframe: https://github.com/martijnversluis/ChordSheetJS/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3AChordPro6
