### ISSUE TITLE
Add support for Non-Monospace fonts for converting to ChordPro

### ISSUE THREAD

**Issue by Rexadev** [martijnversluis/ChordSheetJS#977]
Add support for Non-Monospace fonts for converting to ChordPro

Example -
 https://www.e-chords.com/chords/taylor-swift/back-to-december uses `Arial` for chords and `Poppins Puritan` for title
unlike https://ultimate.ftes.de/ uses monospaced, ultimate-guitar.com uses robotomono, https://www.guitaretab.com uses monospace
### Calibri
![image](https://github.com/ChordPro/chordpro/assets/62152714/b5689ce5-08c4-4b21-a38a-bfecb53e0855)

### Cansolas
![image](https://github.com/ChordPro/chordpro/assets/62152714/cf1d57b2-af7d-4ac0-a0eb-2f3707f24220)

**Comment by martijnversluis** [comment]
@Rexadev Unfortunately I don't think there is a way to make this always work 100%. If you agree I'd like to close this issue.

**Comment by Rexadev** [comment]
@martijnversluis Merge/copy this tread to https://github.com/martijnversluis/ChordSheetJS/issues/955 and delete this one

**Comment by martijnversluis** [comment]
Closed in favor of #955
